version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    # volumes:
    #   - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    depends_on:
        - prometheus
    ports:
        - "3000:3000"

networks:
  default: